# Module 3
#   Programming Assignment 4
#     Prob-5.py

# Riley Hewes

def main():
    try:
        x = eval(2)
        print("x:", x)
    except:
        print("There was an unexpected error.")

main()